# Generated by Django 3.0.3 on 2020-07-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueTokenUser',
            fields=[
                ('token', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'UniqueTokenUser',
            },
        ),
    ]
