# Generated by Django 3.0.3 on 2020-03-01 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usersauth',
            fields=[
                ('token', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('id', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='acc_base.Users')),
            ],
            options={
                'db_table': 'UsersAuth',
                'managed': True,
            },
        ),
    ]
