# Generated by Django 3.0.3 on 2020-02-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccBase',
            fields=[
                ('id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=35)),
                ('password', models.IntegerField(default=0)),
            ],
        ),
    ]
