# Generated by Django 3.0.3 on 2020-03-22 13:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('followers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, size=None)),
            ],
            options={
                'db_table': 'user_followers',
            },
        ),
    ]
