# Generated by Django 3.0.3 on 2020-03-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollower',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('follower', models.IntegerField()),
            ],
            options={
                'db_table': 'user_follower',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.DateTimeField()),
                ('img', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'photo_base',
                'unique_together': {('id', 'img')},
            },
        ),
        migrations.DeleteModel(
            name='UserFollowers',
        ),
    ]
