package com.example.flex

object MainData {
    val BASE_URL = "sleepy-ocean-25130.herokuapp.com"
    val HEADER_REFRER = "Referer"
    val URL_PREFIX_TV_SHOWS = "tv_shows"
    val URL_PREFIX_ACC_BASE = "acc_base"
    val URL_PREFIX_USER_PROFILE = "user_profile"
    val URL_PREFIX_HOME="home"
    val HOME="home"
    val CHECK_LOG="check_log"
    val LIKE="like"
    val COMMENT="comment"
    val FOLLOW_API = "follow"
    val LOGIN="login"
    val LOGOUT="logout"
    val FORGOT_PASS="forgot_pass"
    val RESET_PASS="reset_pass"
    val REGISTRATON="registration"
    val CRSFTOKEN = "crsftoken"
    val VIEW_ACC="view_acc"
    val SEND_IMAGE="add_post"
    val VIEW_PHOTO="view_photo"
    val SESION_ID = "session id"
    val YOUR_ID="your id"
    val ERR_403=403
    val ERR_401=401
    val VIEW_ALL_POSTS="view_all_posts"
    val TAG_COMMENT="comment"
    val TAG_LIKE="like"
    val TAG_SEARCH="search"
    val TAG_GET_FOLLOWERS_COUNT="get followers count"
    val TAG_GET_FOLLOWING_COUNT="get following count"
    val TAG_FOLLOW="follow"
    val TAG_VIEW_ACC="view acc"
    val TAG_FORGOT_PASS="forgot pass"
    val TAG_CHANGE_PASS="change pass"
    val TAG_VIEW_PHOTO="view photo"
    val TAG_DOWNLOAD_PHOTO="download photo"
    val TAG_VIEW_ALL_POSTS_HOME="view all posts home"
    val TAG_VIEW_ALL_POSTS_ACCOUNT="view all posts account"
    val TAG_LOGIN="login"
    val TAG_LOGOUT="logout"
    val TAG_CHECKLOG="checklog"
    val TAG_REGISTER="register"
    val TAG_UPLOAD="upload"
}