# Generated by Django 3.0.3 on 2020-05-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('chat_ava', models.CharField(blank=True, max_length=100, null=True)),
                ('chat_admin', models.IntegerField()),
                ('chat_members', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.IntegerField()),
                ('date', models.IntegerField()),
            ],
            options={
                'db_table': 'message',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ChatMembers',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'chat_members',
                'unique_together': {('chat_id', 'user_id')},
            },
        ),
    ]
